### ISSUE TITLE
user profile page should open "general" section by default

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#101]
Users are normally interested in changing the general parameters when visiting their profiles.  The "general" section should be opened when visiting this page by default, rather than the "summary" section.

**Comment by rbf** [comment]
I'm not sure about this. Users can also expect to see which email they've configured within the application.

I'd rather go a step further and challenge the global usage of collapsible section across the application. There are some cases when this doesn't have to be the best solution, and this could be a good example, since both `Summary` and `Gobal` sections make sense to be visible to the user when landing in the profile page.

Any opinions on this?

**Comment by mebster** [comment]
If they are both useful at the same time, either merge them or allow several sections opened at the same time?

**Comment by schaubl** [comment]
At least the `General` section should always be the second one. #84 
And the `Summary` section should have an other name. #83

In the futur, the `General` section should be call something like `Defaults` because everything except the SSH keys will become default values and SSH keys may be added into a `Credentials` resource.

**Comment by rbf** [comment]
Discussed with @loomis. This issue is not relevant anymore. Closing issue.
