### ISSUE TITLE
remove "select" button when choosing a published image

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#102]
Published images are always only the exact version of the module.  Consequently, when a user is selecting a published image, the "select" button (which chooses the latest version) should be removed or greyed out.

**Comment by rbf** [comment]
New UI (version > 2.4) doesn't has this bug because the `Published Apps` section is not available within the chooser. The root view shows only the `Projects` section when in the chooser:

![screen shot 2015-03-02 at 07 59 21 copy](https://cloud.githubusercontent.com/assets/807084/6436590/9ab4faca-c0b2-11e4-923a-999d608a9ddb.png)

IMO this behaviour is correct, since it would be confusing to use published apps: this would suppose to disable the `Select` button _only_ when accessing the module from the `Published Apps` section, but not when accessing the same version navigating through the `Projects` section.

@mebster 
Please close this issue, if you agree.

**Comment by mebster** [comment]
I'm not sure this is right. Unless we have search enabled in the chooser, find base OS is difficult and requires prior knowledge. Using the app store curated images for me is right.

**Comment by rbf** [comment]
Ok.

In that case I'd suggest that the `Select` button is always disabled when accessing a published app, even if not accessed via the `Published Apps` section but via project navigation, to handle the mentioned incoherence:

> this would suppose to disable the Select button only when accessing the module from the Published Apps section, but not when accessing the same version navigating through the Projects section.

And to make it more clear, I'd add a fixed info alert always when viewing a published module (s. #211)

**Comment by mebster** [comment]
Sounds good to me

**Comment by rbf** [comment]
IMO this point is today still relevant. Promoting to `Proposed for Sprint`.
