### ISSUE TITLE
New layout of Modules's scripts

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#121]
![new script section](https://f.cloud.github.com/assets/2462866/2423751/83bc0e96-ab9e-11e3-8837-733df507df89.png)

**Comment by schaubl** [comment]
Since slipstream/SlipStreamServer#267 and slipstream/SlipStreamClient#83 are done, I think this is the perfect moment to revive, discuss and implement this issue.

@mebster and/or @loomis can you consider this issue for the next sprint ?

**Comment by rbf** [comment]
This issue is somehow outdated since now the `Scripts` section is called `Application Workflows` (see screenshots below).

![screen shot 2016-04-14 at 17 44 22](https://cloud.githubusercontent.com/assets/807084/14534270/9f218a30-0268-11e6-945b-53887fac122f.png)

Closing it in favour of the more recent https://github.com/slipstream/SlipStreamUI/issues/418.
