### ISSUE TITLE
Auto refresh the dashboard

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#132]
The values in the different section should be periodically refreshed

**Comment by rbf** [comment]
@mebster:

The dashboard can probably be refreshed less frequently than the run page, which currently is automatically refreshed in the background every 15s. I guess a minute should be ok for the ok for the dashboard. Or even less, because auto-refresh jobs are automatically re-run when the tab is reopened, ensuring that the values are up to date when switching back to the dashboard tab.

What do you think?

**Comment by loomis** [comment]
Because I'd prefer to follow my applications from the dashboard, I would argue that it should be updated at least as frequently as the run page. Ideally, I'd normally only look at the dashboard and would open the run page only to find details when debugging a problem.

**Comment by sixsq-hudson** [comment]
inc

**Comment by rbf** [comment]
I finished the auto-refresh of the dashboard, see commits above. It was trickier than I though because there are several requests being done at the same time to get updated data.

But now, **it's a pleasure to use!** As @loomis mentioned, with an auto-refreshing dashboard you stay there the whole day.

Indeed, once we have the `Terminate` button and the `service url`, we don't need the `run` page but for debugging. And when those 2 points are also implemented (during the current iteration), the `POST` on `/run` can redirect to the dashboard directly, also as @loomis mentioned.
:sunglasses:  :+1:

As @loomis suggested, I created following issue to track the change in the `POST` behaviour:
https://github.com/slipstream/SlipStreamServer/issues/455
