### ISSUE TITLE
System configuration page should reload when the save operation succeed.

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#169]
To allow to add/remove connector tab when a connector is added/removed.

**Comment by rbf** [comment]
I tried to follow the redirect in the response in `PUT http://localhost:8080/configuration` and encountered an inconsistency on how we handle responses:

1. `PUT http://localhost:8080/configuration` and `PUT http://localhost:8080/service_catalog` (at least) reply with a `Status Code: 303 See Other` and a corresponding `Location` header.

1. `PUT http://localhost:8080/user/username` and `PUT http://localhost:8080/module/*` (at least) reply with a `Status Code: 200 OK` **and** a `Location` header.

The issue is that the redirect triggered by the `303` is handled on a deeper layer, so that the AJAX request handler only _sees_ the redirected answer. In those cases the answers that the AJAX handler receives are `Status Code: 200 OK` **without** a `Location` header served by the request that received the redirect (e.g. `GET http://localhost:8080/configuration`).

In the other cases, the server replies that the `PUT` request worked as expected (`Status Code: 200 OK`) and indicates a `Location` header with the updated resource, leaving the possibility to the AJAX handler to act accordingly as needed.

After consulting several sources<sup>†</sup>, I found that a canonical way to deal with our case (i.e. acknowledge that the transaction was successful and tell the client where to go next, without forcing it to go) is the `Status Code: 200 OK` **plus** a `Location` header, as mentioned in point 2 above. As the the entry `HTTP_location` in the Wikipedia states<sup>1</sup> suggests in the point 2:

> The HTTP Location header field is returned in responses from an HTTP server
> under two circumstances:
>
> 1. To ask a web browser to load a different web page (URL
> redirection). In this circumstance, the Location header should be sent
> with an HTTP status code of 3xx. It is passed as part of the response
> by a web server when the requested URI has:
>   - Moved temporarily;
>   - Moved permanently; or
>   - Processed a request, e.g. a POSTed form, and is providing the result
>     of that request at a different URI
>
> 1. To provide information about the location of a newly created
> resource. In this circumstance, the Location header should be sent
> with an HTTP status code of 201 or 202.<sup>2</sup>

If you agree, we should update `/configuration` and `/service_catalog` resources to reply with a `Status Code: 200 OK`.

That would allow to correctly handle the subject reported by this issue.



<sup>†</sup>Sources:

- <sup>1</sup> http://en.wikipedia.org/wiki/HTTP_location
- <sup>2</sup> Richardson, Leonard (2007). RESTful Web Services. Sebastopol: O'Reilly. pp. 228–230
- REST in Practice, pp. 68-69
- RESTful APIs, pp. 37-38
- http://www.alanflavell.org.uk/www/post-redirect.html
- http://redirectdetective.com/redirection-types.html

**Comment by schaubl** [comment]
Related: slipstream/SlipStreamServer#213

**Comment by rbf** [comment]
Waiting for slipstream/SlipStreamServer#213.

**Comment by schaubl** [comment]
The configuration page doesn't exist anymore
