### ISSUE TITLE
if deployment has a "production" flag set, then confirm termination with dialog

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#196]
If a run has a "production" flag set, then the UI should pop up a confirmation dialog when the termination button is pressed.  This ensures that the user really wants to terminate a production service.

Like tags, this flag should be able to be set at any time.  If set then unset, there should probably also be a warning about this as well.

**Comment by rbf** [comment]
This needs more discussion.

A flexible and quick way to achieve that could be via tags, giving a special meaning to some tags like: `prod`, `production` or `protected`.
It would be anyway useful if tags could be set up at run start within the `Run deployment` dialog. This would allow to both set a name for the run (simply using a tag for that) and to set the run as `production`. In that case, auto-completion for the tag field would be almost a must.

**Comment by rbf** [comment]
This issue is somehow outdated since now `Terminate` button always asks for confirmation, from both the `run` page and the dashboard (see screenshots below). Flagging it as `✖︎ Outdated - Flagged for deletion` for discussion.

## Confirmation dialog for `Terminate` from `run` page

![screen shot 2016-04-14 at 17 17 05](https://cloud.githubusercontent.com/assets/807084/14533366/14fc1c88-0265-11e6-8ebc-92b5c3caee2a.png)


## Confirmation dialog for `Terminate` from dashboard

![screen shot 2016-04-14 at 17 16 41](https://cloud.githubusercontent.com/assets/807084/14533362/10a18902-0265-11e6-8eb0-9d109165e721.png)

**Comment by rbf** [comment]
Discussed with @loomis. Moving to `Top of Backlog`.

As suggested by @loomis, it could be implemented disabled the termination button for the runs flagged as production, and force the user to remove the flag in order to be able to terminate it.

If the flag is implemented as an additional property of a run, the corresponding issue in the Server repo must be added.
