### ISSUE TITLE
Explore and select solution for guide tour for Alice

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#197]
This tour should be an interactive step by step tutorial, with the aim for Alice to be running our Word Press example and terminating it.

**Comment by schaubl** [comment]
Tour libraries:
- Intro.js: http://usablica.github.io/intro.js/
- Bootstro.js (Bootstrap equivalent of Intro.js): http://clu3.github.io/bootstro.js
- jQuery Power Tour: http://www.jquerypowertour.com
- Others: http://www.webresourcesdepot.com/11-awesome-jquery-site-tour-plugins-for-guiding-users-with-style/

**Comment by rbf** [comment]
There are indeed quite a lot of javascript libraries to do application tours as these two compilations below indicate:

- Show HN: Weekend project, Intro.js | Hacker News
https://news.ycombinator.com/item?id=5380056

- A list of product tour plugins for onboarding - Designer News
https://news.layervault.com/stories/15273-a-list-of-product-tour-plugins-for-onboarding

After having quickly reviewed some of them, they seem to work quite similarly, so that I'd start using `intro.js` or `boostro.js` to begin with, and we can easily upgrade to another library is need be:

- Intro.js | Better introductions for websites and features with a step-by-step guide for your projects.
http://usablica.github.io/intro.js/
https://github.com/usablica/intro.js

- Bootstro.js demo
http://clu3.github.io/bootstro.js/
https://github.com/clu3/bootstro.js

`WalkMe` and `PowerTour` are not open source, so that we cannot use it on SlipStream:

- Pricing - WalkMe
http://www.walkme.com/pricing/

- JavaScript - Power Tour - Powerful Creative jQuery Tour Plugin | CodeCanyon
http://codecanyon.net/item/power-tour-powerful-creative-jquery-tour-plugin/3246071

Other interesting options (mentioned in the compilations above) are:

- Tourist.js
http://easelinc.github.io/tourist/

- Shepherd — Guide your users through a tour of your app.
http://github.hubspot.com/shepherd/docs/welcome/

- jQuery TourBus
http://ryanfunduk.com/jquery-tourbus/

**Comment by schaubl** [comment]
I think Bootstro.js is the one we need because it's the equivalent to intro.js but with Bootstrap.
And we use Bootstrap :)

**Comment by schaubl** [comment]
Bootstro.js was choosen.
