### ISSUE TITLE
Allow 'purge' feature to delete all versions of a module in a single action

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#21]
Should make sure enough confirmation is requested.

Alternatively, mark the module as deleted and don't display it (less destructive)

**Comment by rbf** [comment]
I find this is still relevant. Suggestion:
- The modal dialog appearing when clicking the 'Delete' button offers 3 buttons (1 more than now) with: `Cancel`, `Delete module`, `Delete only this version`
- Instead of asking 10 times for confirmation, display an `undo` link once the module or version had been deleted (_"allow user mistakes, and help recover from them"_).

**Comment by rbf** [comment]
IMO this point is today still relevant.

**Comment by schaubl** [comment]
This has been done
