### ISSUE TITLE
Missing HNX image top right corner on login page

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#219]
![screen shot 2015-03-09 at 08 15 47](https://cloud.githubusercontent.com/assets/419519/6551188/9f3bf594-c634-11e4-9ce1-4482aedc0a4b.png)
![screen shot 2015-03-09 at 08 15 32](https://cloud.githubusercontent.com/assets/419519/6551189/9f3e01ea-c634-11e4-82a8-f8947b31809c.png)

**Comment by rbf** [comment]
This is not a bug: the logo is missing on purpose when the user is NOT logged in for two reasons:

1. To differentiate from the logged-in state, and

1. because there is a big HelixNebula logo in the middle of the page on the login page.

So, closing it as `Rejected`. Please re-open if you disagree.
Cheers.
