### ISSUE TITLE
Login page may appear in the Reports tab on the run when cookie expires and the refresh is on.

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#242]
This happens on the run with auto-refresh when Reports tab is opened.

![screen shot 2015-03-25 at 14 42 01](https://cloud.githubusercontent.com/assets/353767/6825843/a43067da-d2fd-11e4-9634-f6de94a12a17.png)

**Comment by schaubl** [comment]
And the text in the "header" part of the page is not the good one.

**Comment by loomis** [comment]
The general behavior of the UI should be changed to more reasonably handle the case when the cookie expires while a user has a SlipStream page open.  The text below is a suggestion. 

For the reports section in particular, the UI is requesting information from the server and just dumping the html response to the page.  The request for the reports should **not** follow redirects and follow the suggestion below when a 401 is detected. 

In general if any query on a page returns a 401 response, then a dialog should be raised to inform the user that he/she's been logged out and offer to 1) close the dialog and return to the page or 2) go directly to the login page and return to this page.  This should be different than the dialog you'd see for a lost/timed-out connection; this dialog should not go away without explicit action from the user.

Any automatic refresh of the page should be turned off when a 401 is encountered.

The dialog should warn the user that any information being edited may be lost; hence the option to return to the page to allow the user to save the information elsewhere.  Another option would be to perform the login through another window and then allow the user to save the edits after the cookie has been refreshed.

**Comment by rbf** [comment]
I agree completely that the behaviour should be enhanced within the lines that you described. However there were 2 problems preventing that:

1. Redirection is handled on a deeper layer, so that the AJAX request handler only sees the redirected answer. See this [comment](https://github.com/slipstream/SlipStreamUI/issues/169#issuecomment-74299770) of the issue #169 for a detailed discussion.

1. Moreover, as stated in the title of SlipStream/SlipStreamServer#422, requesting a page without being authenticated redirects to /login page without returning a 401 (Unauthorized) status code.

This might have changed with `v2.19.1`, as the following `curl` shows, so I'm not sure that this is still the case.

```
$ curl -fL nuv.la
curl: (22) The requested URL returned error: 401 Unauthorized
```

So, if `2.` is fixed, `1.` would not be relevant anymore, so this issue can now be handled.

**Comment by rbf** [comment]
This issue is still present on `v3.1`:

![screen shot 2016-04-14 at 18 09 12](https://cloud.githubusercontent.com/assets/807084/14535056/49c15436-026c-11e6-99bd-af9fbb981408.png)

To reproduce:

1. Go to a run page (even a terminated one), and open the `Reports` section.
1. Open a second browser tab and logout the user from SlipStream.
1. Go to the first tab, and the `Reports` section will show the login page.

Promoting to `Proposed for Sprint`.
