### ISSUE TITLE
Runs not ordered by time correctly

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#265]
![screen shot 2015-04-04 at 14 48 09](https://cloud.githubusercontent.com/assets/419519/6992675/f0e8dbb4-dad9-11e4-8b48-bf0f1d1a41dd.png)
![screen shot 2015-04-04 at 14 48 32](https://cloud.githubusercontent.com/assets/419519/6992674/f0675990-dad9-11e4-85b0-79592842f94a.png)

See ready run on April 2nd

**Comment by schaubl** [comment]
It looks like this happens when the Run is a multicloud Run.

I checked the server code and they are sorted by `start time`:
```java
critQuery.orderBy(builder.desc(rootQuery.get("startTime")));
```
So it seems to be an issue of the UI.
All multicloud Runs are at the end of the list.

![ui-runs-list-order-bug](https://cloud.githubusercontent.com/assets/2462866/6995038/c08b6996-db2e-11e4-8151-3bf0c5ff5a9d.png)

The XML version is sorted correctly.
