### ISSUE TITLE
Pagination not working on the Run section of a module

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#266]
When we click on a page, the page is not loaded.

**Comment by rbf** [comment]
I enabled pagination for the run section in the image and deployment pages with the two commits above.
However I realised that there is **no module filter available** server side to use it in the URL to narrow the runs list to a given module, or I haven't found it. We can currently request `/run?cloud=Cloud2&limit=5` but not `/run?cloud=Cloud2&limit=5&module=examples/wordpress/150`.

Any ideas?

**Comment by mebster** [comment]
I would have thought that the entire query fragment should have being passed through.

**Comment by rbf** [comment]
My explanation was not clear enough. The issue is that when we request the server `/run?cloud=Cloud2&offset=0&limit=20&module=examples/wordpress/150` only the query params `cloud`, `offset` and `limit` are taken into account.

So the question is if there is a `module` filter at all and if yes, how it's used.

Cheers.

**Comment by rbf** [comment]
The expected format was:
```
/run?cloud=&offset=0&limit=20&moduleResourceUri=module/example/wordpress/150
``` 
(see comment in last commit 9ee1439)
Thanks @mebster :bow:
