### ISSUE TITLE
Language issue with the query parameter 'lang'

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#269]
When `lang` is added to the URL there are the following issues:
- The `lang` parameter is not added to links on the page. So only the current page will be translated.
- The `lang` parameter is not forwarded to subqueries like on the dashboard for the VMs list and the Run list. So these list are not translated.

One solution would be to add `lang` to all links of the page when `lang` is set.
Another solution would be to add the value of `lang` into the cookie.

**Comment by schaubl** [comment]
I prefer the second solution.

**Comment by rbf** [comment]
Rejected: the language customisation of the UI (and thus the query parameter `lang`) is not an advertised feature. Therefore the query parameter `lang` is not expected to be a mechanism to specify the language of the UI. It is there only to quickly test the rendering in another language.

Instead of this bug, I created an issue to properly implement this feature.
