### ISSUE TITLE
Add 'Terminate' button to dashboard (with warning)

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#395]
User request: https://sixsq.freshdesk.com/helpdesk/tickets/625

**Comment by loomis** [comment]
This is a terminate button for the application as a whole.  Separate ticket will be created for terminating VMs.

**Comment by rbf** [comment]
There are two ways to implement, with different implementation costs:

1. The terminate button redirects to the corresponding run page, directly opening the confirmation dialog to terminate the run. (Compare it with the current implementation of the Delete action on the `/users` page).
  - **implementation cost:** 15min
  - **advantage:** it brings the user to the page of the run, showing more context about the application about to the terminated, so that the user can double-check it before pressing the button
  - **disadvantage:** an extra request

1. The terminate button does not redirect to the corresponding run page, and opens the confirmation dialog to terminate the run directly in the dashboard page.
  - **implementation cost:** half day (a new modal dialog has to be created and wired)
  - **advantage:** no extra request and staying on the dashboard
  - **disadvantage:** lack of context while terminating the app

I see +/- points for both approaches. What do you prefer?

**Comment by loomis** [comment]
I'd vote for 2.  Eliminating unnecessary context switching, for me, improves the user's workflow.  If users really want to understand the context of the application, they can go to the run page and then terminate the application from there.

**Comment by mebster** [comment]
I agree with @cal.  But we need to ensure we can delete several runs, as each termination takes a while.
