### ISSUE TITLE
show only configured connectors in UI

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#459]
Throughout the UI, show only configured connectors:

 - [ ] Remove entirely (rather than disabling) the unconfigured connectors in the cloud dropdown list for deployments/nodes.
 - [ ] Only show configured connectors in the user profile in view mode.
 - [ ] Provide a "plus" button to add new connectors to the user profile in edit mode.
 - [ ] Provide a "delete" button to remove a specific connector from the user profile.
 - [ ] The dashboard should only show the gauges, tabs, etc. for configured connectors.

The service catalog (if enabled) should continue to show entries related to all clouds.

**Comment by rbf** [comment]
Still have to discuss further on that but could go for it.

**Comment by rbf** [comment]
IMO this issue suggests a rather big change, and therefore it has to be well designed, planned and tested. Each of the points suggested above could be an issue on its own, but we can leave them together if we want to consider it as an atomic change, i.e. if none of the points makes sense deployed individually. Otherwise we could do it in three smaller issues:
- remove unconfigured clouds from dropdowns (first point)
- enhance connectors configuration in user profile page (points 2-4)
- remove gauge for  unconfigured clouds from dashboard (last point)

**Comment by loomis** [comment]
Feel free to split the tickets if you'd like.  The order of importance for the three points are 1, 3, 2.

**Comment by rbf** [comment]
Issue split in the three issues mentioned above: #508, #509 and #510.
Closing this one.
