### ISSUE TITLE
error for users with periods in their name

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#474]
There is apparently an issue where a username with a period in their name is confused with a parameter.  The screenshot shows the problem:

![error-for-user-with-period](https://cloud.githubusercontent.com/assets/490506/11085487/47b36908-8847-11e5-82b3-6f4883ea973e.png)

**Comment by rbf** [comment]
I had a look at this issue and first of all, I wonder how there can be a user with a dot in the username, since it's not possible via the UI as self-sign-up:

![screen shot 2015-11-11 at 09 30 13](https://cloud.githubusercontent.com/assets/807084/11087095/82ac4600-8857-11e5-88ae-aecfff67b7ac.png)

nor creating a user as `super`:

![screen shot 2015-11-11 at 09 27 57](https://cloud.githubusercontent.com/assets/807084/11087096/82d61516-8857-11e5-979d-bd2914193bda.png)

Secondly, I see a similar alert when I come back to a browser tab with the dashboard open after having logged out and logged in with another user:

![screen shot 2015-11-11 at 09 22 32](https://cloud.githubusercontent.com/assets/807084/11087125/be443268-8857-11e5-89b4-43b5877c78d9.png)

Might this be related?

**Comment by rbf** [comment]
As discussed with @mathiasslawik, he was able to create a user with a dot in the username because the `username` field was pre-filled by his browser (Chrome). I've created an issue to properly fix this (#476).

@mathiasslawik will create a new user without the dot.
