### ISSUE TITLE
Add "Copy Run ID" button to allow to copy run ID

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#490]
Run ID is used very often outside of SS UI for example with CLIs.
It would be useful to have such feature (as a `button` or something) not only on the Run, but also on Dashboard - maybe on the dropdown when hoovering over the link of the run (not sure if this is possible though)?

**Comment by rbf** [comment]
Very sensible suggestion. :+1: 

For reference, because of security reasons, there is no proper way (I'm aware of) to directly allow the browser to automatically populate or read the system's clipboard, unless it's using Flash.

In the first link below, a SO answer suggests to open an alert to let the user `cmd-C` or `ctrl-C`it. The second link points to `zeroclipboard`, one of the standard libraries to do it using Flash.

- How do I copy to the clipboard in JavaScript? - Stack Overflow
  http://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript

- `zeroclipboard`
  https://github.com/zeroclipboard/zeroclipboard

**Comment by konstan** [comment]
Flash? :) oops.   What about something similar to 
<img width="772" alt="screen shot 2015-11-30 at 17 05 56" src="https://cloud.githubusercontent.com/assets/353767/11476762/c1870810-9784-11e5-8b4c-fc64f2f30c3c.png">

I don't know how this is done, but looks like w/o Flash.

**Comment by schaubl** [comment]
@konstan: It's done via Flash. If you disable Flash you will see.

**Comment by konstan** [comment]
Really? :) ok trying.

**Comment by konstan** [comment]
Just disabled Flash (Chrome)... but still can copy the repo URL on the GH page.

**Comment by rbf** [comment]
It shouldn't work [without Flash](http://i1.wp.com/lolzombie.com/wp-content/uploads/2009/08/withoutflash.jpg). And I'd vote to avoid using it. There are some people [serious about it](http://occupyflash.org).

**Comment by konstan** [comment]
Just disabled Flash in Safari, restarted and wasn't able to copy the URL.  So, this confirms @schaubl 's  statement that github does this with Flash.   I didn't expect that.
