### ISSUE TITLE
UI present 2 times the same VMs 

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStreamUI#533]
In Opennebula I have 7 running VMs. Describe instance return a consistent list but the UI present 2 times the same VMs. 

SLIPSTREAM_CONNECTOR_INSTANCE=opennebula opennebula-describe-instances --endpoint https://172.16.0.1:2634/RPC2 --username ssuser --password sspass
id, state, ip, cpu [nb], ram [MB], root disk [GB], instance-type [name]
73, Running, 172.16.0.13, 1, 512, 271, micro
75, Running, 172.16.0.15, 1, 512, 271, micro
76, Running, 172.16.0.16, 1, 512, 271, micro
78, Running, 172.16.0.10, 1, 512, 271, micro
79, Running, 172.16.0.11, 1, 512, 271, micro
81, Running, 172.16.0.14, 1, 512, 271, micro
82, Running, 172.16.0.17, 1, 512, 271, micro
![vms](https://cloud.githubusercontent.com/assets/5518233/12800202/90cceb9a-cad3-11e5-8378-d08235c6a92f.PNG)

**Comment by schaubl** [comment]
@0xbase12 

This is because these instances have been describes by two different SlipStream users who share OpenNebula credentials (`nuvlabox` and `super`).

And because you are (probably) connected as `super`, you can see VM described by all users.
If you log in with the user `nuvlabox` it will not be duplicated.

**Comment by 0xbase12** [comment]
Thanks Lionel for explanation

**Comment by mebster** [comment]
We are discussing this dashboard inconsistency this Friday with @rbf

_________
Marc-Elian Bégin
CEO, Co-Founder
SixSq
Geneva, Switzerland
meb@sixsq.com
+41 77 44 68 119
@lemeb
@sixsq
sixsq.com
