### ISSUE TITLE
Edition of user profile on safari automatically pre-fills some fields

### ISSUE THREAD

**Issue by st** [slipstream/SlipStreamUI#630]
On safari, before clicking `edit` (notice API key for example):

![before-edition](https://cloud.githubusercontent.com/assets/16004/16143743/01c20628-346f-11e6-89f3-648d92add014.png)

After clicking `edit`, fields are filled with autofill information 

![after-edition](https://cloud.githubusercontent.com/assets/16004/16143770/3059d150-346f-11e6-8521-c23649cc45c2.png)

**Comment by mebster** [comment]
This is indeed frustrating and can cause great confusion.

**Comment by rbf** [comment]
After some investigation I found following points:

## What we do now

We already do our best in trying to prevent browsers to autofill values in forms. This is done by setting the attribute `autocomplete="off"` [to the `form` tag](https://github.com/slipstream/SlipStreamUI/blob/d7e0d244c8b3b9ee6de175f8fb3040a2bd26869b/clj/src/slipstream/ui/views/base.clj#L146) itself or [to the individual child `input` tags](https://github.com/slipstream/SlipStreamUI/blob/d7e0d244c8b3b9ee6de175f8fb3040a2bd26869b/clj/src/slipstream/ui/views/base.clj#L253). We do both. You can look for the string `autocomplete="off"` in the HTML of a SlipStream in edit mode.

## Why it does not work

Modern browsers include an integrated password management solution, which will prevent [them from honouring the `autocomplete="off"` flag on login fields](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields). Thus, the cloud credential fields have `name` and `id` attributes like `parameter-exoscale-ch-gva.username--1--value` or `parameter-exoscale-ch-gva.password--2--value`, letting the browser thinking that those are login fields. This is [a](http://stackoverflow.com/questions/468288/input-type-password-dont-let-browser-remember-the-password) [common](http://stackoverflow.com/questions/2530/how-do-you-disable-browser-autocomplete-on-web-form-field-input-tag) [problem](http://stackoverflow.com/questions/3868299/is-autocomplete-off-compatible-with-all-modern-browsers).

## Possible solutions

One solution would be to rename the `id` and the `name` of those fields (not the UI label) to something like e.g. `secret` and `key`, so that the browser don't interpret them as login fields. But this might be a big change server side.

Another workaround would be to change the `id` and the `name` of those fields on the fly with JS to something that does not confuse the browser, and changing it back to the value expected by the browser before sending the form.

**Comment by rbf** [comment]
## Tested solutions

I've come up with several strategies to workaround this issue on Safari (some inspired by what I found on internet), none of which are fully convincing. I've tested them and these are the results. The last one is the less bad, and is currently active on Nuvla for testing.

### Adding fake fields

The trick is trying to add a fake field so that Safari fills those in instead of the fields we are interested on. It would be something in the lines of the following snippet, but is does not work:

```javascript
// SOURCE: http://stackoverflow.com/a/23016234
$('input[autocomplete=off][name*=username]:visible').each(function(){
    $(this).before(
        '<input id="fake_username" name="fake_username" style="position:absolute; top:-100px;" tabindex="-1" type="text" value="Safari Autofill Me">'
        );
});

$('input[autocomplete=off][name*=password]:visible').each(function(){
    $(this).before(
        '<input id="fake_password" name="fake_password" style="position:absolute; top:-100px;" tabindex="-1" type="password" value="Safari Autofill Me">'
        );
});
```


### Making the fields `readonly` until clicking on them

```javascript
$('input[autocomplete=off]:visible:not([readonly])').each(function(){
    $(this)
        .css('background-color', 'white')
        .attr('readonly', 'readonly')
        .focus(function(){
            $(this)
                .removeAttr('readonly')
                .css('background-color', '');
        });
});
```

This works for all but password fields. Safari continues to autofill them. Note that we need only to target the `:visible` fields, since Safari seems to not autofill hidden ones.


### Making the fields `disabled` until hovering on them

```javascript
$('input[autocomplete=off]:visible:not([readonly])').each(function(){
    $(this)
        .css('background-color', 'white')
        .addClass('disabled-to-prevent-autofill')
        .attr('disabled', 'disabled')
        .closest(':not([disabled])')
            .hover(function(){
                $(this)
                    .find('.disabled-to-prevent-autofill')
                        .removeAttr('disabled')
                        .removeClass('disabled-to-prevent-autofill')
                        .css('background-color', '');
            });
});
```

As with the previous case, this works for all but password fields. Note that here we need to attach the event handler on a parent field, because such events are not fired for disabled elements.


### Relying on the non-standard pseudo `:-webkit-autofill`

Previous two methods would be the most reliable... if they would work for the passwords as well. Following method relies on a non-standard pseudo selector and an arbitrary timer, which is not very reliable. Moreover it forces the color of the field to be white again with margins because the Safari flags the fields it pre-filled with a yellow background, and it can not be changed normally by css.

```javascript
// SOURCE: http://stackoverflow.com/a/25828724
setTimeout(function() {
    $('input[autocomplete=off]:-webkit-autofill').each(function(){
        var $this = $(this);
        if ( $this.val() !== $this.attr('value') ) {
            $this
                // SOURCE: http://stackoverflow.com/a/19426087
                .css('-webkit-box-shadow', '0 0 0px 1000px white inset')
                .val($this.attr('value'));
        }
    });
}, 600);
```

This is currently active on Nuvla and works for all fields (including `username`, `password`, `email`...). However there is a visible flicker when we override the values set up by the browser. Moreover the delay of `600` millisecs is found empirically and might break in some cases. Trying to rely on an event like `input` does not work better because the handler is installed after the browser autofilling happened.
