### ISSUE TITLE
run button should be disabled for non-base images if they have not yet been built in any cloud

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#79]
If an image has not been built, then the run button should be disabled.  If the image exists for some clouds but not others, then the error message should suggest using a different cloud infrastructure.

**Comment by rbf** [comment]
Still relevant, but solution not yet well defined.

The information about the _build state_ of an image is not (yet) available in the metadata, so that some work on the Server side will be required.

Besides disabling the `Run` button, we could add also a (fixed) warning with the explanatory message, in the same way that we display the message about viewing an old version of a module.

**Comment by schaubl** [comment]
Related to (or maybe superseded by) #228.

**Comment by rbf** [comment]
Indeed related to #227 (not #228 as specified above). However, not closing this issue, since this point is not fully covered by the mentioned issue, and is still relevant on its own.

**Comment by schaubl** [comment]
This doesn't apply anymore since we can run images which wasn't built.
See slipstream/SlipStreamServer#267 and slipstream/SlipStreamClient#83.

@loomis : Can we close this issue ?

**Comment by loomis** [comment]
Yes, this can be closed as it is (as stated) no longer relevant since we can now run images that haven't been built.
